name: Playwright Tests
on:
  pull_request:
    branches: [main, develop]
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test > playwrite-results.txt

      - name: Comment on PR with test results
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('playwright-results.txt', 'utf8');
            const prNumber = context.payload.pull_request.number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `## Playwright Test Results\n\n\`\`\`\n${results}\n\`\`\``
            });
